export const DATA = {
  sectors: ['Professional Services','Technology','Financial Services','Legal','Healthcare','Media & Creative','Consulting','Real Estate','Recruitment','Accounting & Finance','EdTech','Insurance'],
  locations: ['Central London','the City of London','Canary Wharf','Shoreditch','Midtown','the West End','Manchester city centre','Birmingham','Bristol','Leeds','Edinburgh'],
  angles: [
    'Workplace refresh / fit-out opportunity',
    'Office relocation and new environment build',
    'Post-merger or post-acquisition consolidation',
    'Hybrid workspace transformation',
    'HQ upgrade — brand and talent retention play',
    'Lease-end triggered reconfiguration',
    'Expansion into additional space',
  ],
  timings: ['6–12 months','12–18 months','18–24 months','within the next 6 months'],
  triggers: [
    'Hiring growth visible on LinkedIn — headcount pressure on existing space',
    'Company age and growth stage make a lease event statistically likely',
    'Website language reflects workforce and culture investment',
    'Recent senior hires in operations or workplace functions',
    'Multi-site footprint suggests rationalisation opportunity',
    'Brand refresh signals commercial momentum and possible environment change',
    'Listed growth plans or expansion language in public filings',
    'Active recruitment for facilities or real estate functions',
  ],
  gapPool: [
    'Lease position and renewal date unconfirmed',
    'Current headcount and growth trajectory not fully validated',
    'No named stakeholder identified yet',
    'Physical office size and configuration unknown',
    'Ownership vs. tenant status unclear',
    'Budget cycle and procurement process unknown',
    'Internal workplace decision-maker not confirmed',
  ],
  dmPool: ['Facilities Manager','Head of Workplace','Chief Operating Officer','Head of Real Estate','Operations Director','Office Manager','Chief People Officer','Head of Projects'],
  buyingMotions: ['Tenant-led','Landlord-led','Operations-led','Leadership-led','Finance-approved','HR / People-led'],
  discoveries: [
    'How is your current space performing against how your team actually works today?',
    'What is your current lease position — are you coming up to a review or renewal?',
    'Has your headcount changed significantly in the last 12 months?',
    'Do you have a named person carrying workspace or facilities responsibility?',
    'What would a better working environment mean for your team and business?',
    'Have you had any conversations internally about the office and where it is headed?',
    'What does your current space say about your brand to clients and candidates?',
  ],
  objections: [
    '"Not the right time right now" → Ask: when does your lease come up for review? That is usually the forcing function.',
    '"We have someone for that" → Acknowledge, then ask: are they looking at a full fit-out or just maintenance?',
    '"We are happy with our current space" → Ask: what would make it even better for the team?',
    '"Budget is tight" → Pelham works across a wide range of project sizes — worth understanding the scope first.',
    '"We are looking at other providers" → Good — when you compare, make sure you compare like-for-like on design capability and project management.',
  ],
  openerScripts: [
    'Hi [NAME], I have been looking at [COMPANY] and I was curious about how your team is managing the workspace as you grow. We work with [SECTOR] businesses at exactly the inflection point where space starts to constrain rather than enable. Worth a quick conversation?',
    'Hi [NAME] — [SENDER] from Pelham Interiors. Quick question: is your current office set up for how your team actually works today? [Pause] That is interesting — what is driving that thinking?',
  ],
  projectLabels: {
    auto_detect: 'Auto-detect',
    fit_out: 'Fit-out',
    refurbishment: 'Refurbishment',
    relocation: 'Relocation',
    reconfiguration: 'Reconfiguration',
    expansion: 'Expansion',
    consolidation: 'Consolidation',
    workplace_consultancy: 'Workplace consultancy',
    furniture_move: 'Furniture / move management',
  } as Record<string, string>,
};
